### PR TITLE
Attempt to fix daemonsauce for node 0.12+

### PR DESCRIPTION
**Pull request by heyvito**
This updates `daemonsauceNative.cc` to use APIs from Node 0.12+

### CODE REVIEW

**Comment by nicks** [comment]
hmmm...so this will actually break compatibility with node 0.10? I think the recommended way to do this now is to use the NAN macros? https://www.npmjs.com/package/nan

**Comment by victorgama** [comment]
You're right. Will fix it now.

**Comment by victorgama** [comment]
@nicks Any idea on how to test this? I can successfully call `acquireLock`, but `reopenStdout`, for instance, is giving me a segmentation fault. :disappointed:

**Comment by nicks** [comment]
Ya this package is a PITA to test. I'll see what I can do tomorrow.

**Comment by nicks** [comment]
ok, i think i got a handle on this. can you fill out a quick CLA for us?
https://github.com/Medium/opensource/blob/master/sign-cla.md
thanks again!

**Comment by nicks** [comment]
i also added some unit tests, so if you rebase travis should run them automatically.

**Comment by victorgama** [comment]
CLA signed and email sent. (:
Will rebase in a minute.

**Comment by nicks** [comment]
sorry, this fell off my radar. i'm going to see if i can rebase myself and merge.

**Comment by nicks** [comment]
this was merged as https://github.com/Medium/daemonsauce/pull/10

**Pull request closed without merging**
